export const FETCH_RANKING_LOADING = 'FETCH_RANKING_LOADING';
export const FETCH_RANKING_SUCCESS = 'FETCH_RANKING_SUCCESS';
export const FETCH_RANKING_ERROR = 'FETCH_RANKING_ERROR';

export const FETCH_RECENT_CONTENTS_LOADING = 'FETCH_RECENT_CONTENTS_LOADING';
export const FETCH_RECENT_CONTENTS_SUCCEES = 'FETCH_RECENT_CONTENTS_SUCCEES';
export const FETCH_RECENT_CONTENTS_ERROR = 'FETCH_RECENT_CONTENTS_ERROR';

export const PAGE_CHANGE = 'PAGE_CHANGE';
